#!/bin/sh

DM_VERSION=1.0-SNAPSHOT

# Dirs
REL_SCRIPT_DIR=$(dirname $0)
ABS_LIB_DIR=${PWD}/${REL_SCRIPT_DIR}/../lib

# External libs
COMMONS_CLI_JAR=${ABS_LIB_DIR}/commons-cli-1.2.jar

EXT_LIBS=${COMMONS_CLI_JAR}

# Internal libs
DM_SERVICES_JAR=${ABS_LIB_DIR}/diosmio-services-${DM_VERSION}.jar
DM_SERVER_COMMON_JAR=${ABS_LIB_DIR}/diosmio-server-common-${DM_VERSION}.jar
DM_CLI_JAR=${ABS_LIB_DIR}/diosmio-cli-${DM_VERSION}.jar

DM_CLI_MAIN=net.alaux.diosmio.ui.cli.Main

java -cp ${EXT_LIBS}:${DM_SERVICES_JAR}:${DM_SERVER_COMMON_JAR}:${DM_CLI_JAR} ${DM_CLI_MAIN} $@
