// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiosmioEntity.proto

package net.alaux.diosmio.com.protobuf.proto;

public final class DiosmioEntityProtos {
  private DiosmioEntityProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ArtifactPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
  }
  public static final class ArtifactPB extends
      com.google.protobuf.GeneratedMessage
      implements ArtifactPBOrBuilder {
    // Use ArtifactPB.newBuilder() to construct.
    private ArtifactPB(Builder builder) {
      super(builder);
    }
    private ArtifactPB(boolean noInit) {}
    
    private static final ArtifactPB defaultInstance;
    public static ArtifactPB getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArtifactPB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_fieldAccessorTable;
      }
      
      // Construct using net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.getDescriptor();
      }
      
      public net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB getDefaultInstanceForType() {
        return net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.getDefaultInstance();
      }
      
      public net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB build() {
        net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB buildPartial() {
        net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB result = new net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB) {
          return mergeFrom((net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB other) {
        if (other == net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:net.alaux.diosmio.com.protobuf.proto.ArtifactPB)
    }
    
    static {
      defaultInstance = new ArtifactPB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.alaux.diosmio.com.protobuf.proto.ArtifactPB)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DiosmioEntity.proto\022$net.alaux.diosmio" +
      ".com.protobuf.proto\"&\n\nArtifactPB\022\n\n\002id\030" +
      "\001 \002(\003\022\014\n\004name\030\002 \001(\t2\202\001\n\017ArtifactService\022" +
      "o\n\tblablabla\0220.net.alaux.diosmio.com.pro" +
      "tobuf.proto.ArtifactPB\0320.net.alaux.diosm" +
      "io.com.protobuf.proto.ArtifactPBB;\n$net." +
      "alaux.diosmio.com.protobuf.protoB\023Diosmi" +
      "oEntityProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_alaux_diosmio_com_protobuf_proto_ArtifactPB_descriptor,
              new java.lang.String[] { "Id", "Name", },
              net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.class,
              net.alaux.diosmio.com.protobuf.proto.DiosmioEntityProtos.ArtifactPB.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
