#!/bin/sh

DM_VERSION=1.0-SNAPSHOT

COMMONS_CLI_JAR=${M2_REPO}/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
SLF4J_API_JAR=${M2_REPO}/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar
SLF4J_SIMPLE_JAR=${M2_REPO}/org/slf4j/slf4j-simple/1.6.6/slf4j-simple-1.6.6.jar

DM_SERVICES_IFACE_JAR=${M2_REPO}/net/alaux/diosmio/diosmio-services-interface/${DM_VERSION}/diosmio-services-interface-${DM_VERSION}.jar
DM_CLI_JAR=target/diosmio-cli-${DM_VERSION}.jar

DM_CLI_MAIN=net.alaux.diosmio.ui.cli.DiosMioCli

EXT_LIBS=${COMMONS_CLI_JAR}:${SLF4J_API_JAR}:${SLF4J_SIMPLE_JAR}

java -cp ${EXT_LIBS}:${DM_SERVICES_IFACE_JAR}:${DM_CLI_JAR} ${DM_CLI_MAIN} $@
