#!/bin/sh

DM_VERSION=1.0-SNAPSHOT

COMMONS_CLI_JAR=${M2_REPO}/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
DM_SERVICES_IFACE_JAR=${M2_REPO}/net/alaux/diosmio/diosmio-services-interface/${DM_VERSION}/diosmio-services-interface-${DM_VERSION}.jar
DM_CLI_JAR=diosmio-cli/target/diosmio-cli-${DM_VERSION}.jar
DM_CLI_MAIN=net.alaux.diosmio.ui.cli.DiosMioCli

java -cp ${COMMONS_CLI_JAR}:${DM_SERVICES_IFACE_JAR}:${DM_CLI_JAR} ${DM_CLI_MAIN} $@
