#!/bin/sh
#TODO set absolute path here
export LIB_DIR=../diosmio-web/target/diosmio-web-1.0-SNAPSHOT/WEB-INF/lib
export ANTLR_LIBS=${LIB_DIR}/antlr-3.4.jar:${LIB_DIR}/antlr-runtime-3.4.jar:${LIB_DIR}/ST4-4.0.4.jar

java -cp ${ANTLR_LIBS} org.antlr.Tool src/main/java/net/alaux/diosmio/ui/cli/antlr/DiosMioCli.g

